ALTER TABLE "Run" ADD COLUMN IF NOT EXISTS "elevationGainM" DOUBLE PRECISION;
ALTER TABLE "Run" ADD COLUMN IF NOT EXISTS "elevationLossM" DOUBLE PRECISION;
ALTER TABLE "Run" ADD COLUMN IF NOT EXISTS "avgSpeedKmh" DOUBLE PRECISION;
